# See: https://yamllint.readthedocs.io/en/stable/
---
rules:
  document-start:
    present: true
  document-end:
    present: false
  indentation:
    spaces: 2
    indent-sequences: true
  line-length:
    level: warning
    max: 92
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: enable
  quoted-strings:
    quote-type: double
    required: only-when-needed

ignore-from-file:
  - .gitignore
  - .yamlignore
