# See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
---
name: julia-version
description: Resolve version specifiers into Julia versions
author: Curtis Vogt

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red
inputs:
  version:
    description: >-
      The Julia version specifier to use. Prefer using strings instead of
      numeric values avoid unwanted YAML decimal conversions (e.g. `1.10` would
      will be interpreted as `1.1`). Examples: "1", "1.10", "lts", and "pre".
    required: true
  include-all-prereleases:
    description: >-
      Include prereleases when matching the Julia version specifier.
    default: "false"
  arch:
    description: >-
      Limit the version specifier to Julia versions which support the specified
      architecture. Defaults to using the architecture of the GitHub runner
      executing the action.
    default: ""
  project:
    description: >-
      The path to the Julia project directory or file to use when resolving some
      versions (e.g. "min")'
    required: false
    default: "" # Empty string is a special value which falls back to using JULIA_PROJECT if defined, otherwise "."

# Define your outputs here.
outputs:
  version:
    description: The complete Julia semver.

runs:
  using: node20
  main: dist/index.js
