# See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
---
name: julia-version
description: Resolve version specifiers into Julia versions
author: Curtis Vogt
branding:
  icon: filter
  color: purple
inputs:
  version:
    description: >-
      The Julia version specifier or list of specifiers to resolve. Inputs
      formats supported include scalars, JSON lists, and YAML lists. When
      passing in a scalar prefer using a string instead of a numeric value to
      avoid unwanted YAML decimal conversions (e.g. `1.10` will be interpreted
      as `1.1`).

      Examples: `"1"`, `"1.10"`, "lts", `["min", "lts", "1"]`
    required: true
  include-all-prereleases:
    description: >-
      Include prereleases when matching the Julia version specifier.
    default: "false"
  project:
    description: >-
      The path to the Julia project directory or file to use when resolving some
      versions (e.g. "min")'
    required: false
    default: "" # Empty string is a special value which falls back to using JULIA_PROJECT if defined, otherwise "."
outputs:
  version:
    description: The resolved Julia version
  downloads-json:
    description:
      JSON list of downlaods available for the specified Julia version
runs:
  using: node20
  main: dist/index.js
