---
name: Example
on:
  pull_request: {}
  push:
    branches:
      - main

# These permissions are needed to:
# - Checkout the Git repository (`contents: read`)
permissions:
  contents: read

jobs:
  version:
    name: Resolve Julia Versions
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.julia-version.outputs.unique-json }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Project.toml
        shell: bash
        run: |
          # Need Julia 1.8 for `macos-latest` which defaults to Apple Silicon (aarch64)
          echo -e '[compat]\njulia = "1.8"' >Project.toml
      - uses: ./
        id: julia-version
        with:
          versions: |
            - min  # Oldest supported version
            - lts  # Long-Term Stable
            - 1    # Latest release

  test:
    # e.g. `Julia 1.10.8 - ubuntu-latest`
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    needs: version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ${{ fromJSON(needs.version.outputs.json) }}
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - name: Julia version info
        shell: julia --color=yes {0}
        run: |
          using InteractiveUtils
          versioninfo()
